version: 2
updates:
- package-ecosystem: npm
  directory: "/website"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/playground-api"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/playground-runner"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
