os: linux
dist: xenial
language: php

script:
  - composer install
  - cd e2e
  - composer install
  - php testPharAutoloader.php
  - vendor/bin/phpunit PharTest.php

env:
  global:
    secure: "TbH4BzxhThar4som8lrLvysZe2Unf7LNmbnBma9ZT7v6yYk1RLug9tIltCoktrIRsSuq6usspG1GjmWpb74KTJSXVs3BuR81hM7zH4DKkZZahqhVgz1uOno3qZHCO/K/hSBfS3gkIuTPuYmAOEaSWz26buKwZPQWlSWFWfo3+uvT6jaa+Ry+EWwbtpEQsp7ox3oOomIJg3jwUD9tP7xlyMHDDY1XC8X1uE09KefqUSxeN2id5Yb6kb21+iB9kONImGt0AqUSBOa7iwadizhBMGUs0b9IwVIG4+5V3zIATubqZOTGJQJ/z+XDCY6gUw42TmVThneZVdM9++7XU7mCuIh+5jE1tTgnxuLGubXAAFWLPZN0+VwMnkCCcdccFz313+pSCVgww2lIKn2Ij0fGt3OJyqik8kzDwE7YGuFWJYx21SXTiJy6nXj9T7UYEJbyNMq6PSA/QVUrfnikzJ5024NYs2MhnL7ZPuo364M6I7HkecRVvlSdsI04njjUYpCBVvR+sIEfBzL3YBq3kz8v2Q+V0lY6wsrGDfZdQ1KonbE3XC7ADZSVzzzwcSl2OWwamjbORgr03LoEwJZuk7nYDDzyJU7zwtu4XiagxdudJw+/V/xAhQo079MOiiOP91ZTFm4g18WvDrCSkDUGe3/SIlCy5ESWYQHHNUvaQjb9a28="

jobs:
  include:
    - stage: Tests
      php: 7.1

    - stage: Tests
      php: 7.2

    - stage: Tests
      php: 7.3

    - stage: Tests
      php: 7.4snapshot

    - stage: Tests
      os: windows
      dist: 1803-containers
      language: sh # No PHP currently
      env: PHP_VERSION=7.1.32
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH

    - stage: Tests
      os: windows
      dist: 1803-containers
      language: sh # No PHP currently
      env: PHP_VERSION=7.2.23
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH

    - stage: Tests
      os: windows
      dist: 1803-containers
      language: sh # No PHP currently
      env: PHP_VERSION=7.3.10
      install:
        - choco install php --version=${PHP_VERSION} --package-parameters="/InstallDir:c:\tools\php"
        - choco install composer --ia "/DEV=C:\tools\php"
        - export PATH=/c/tools/php:$PATH

    - stage: Extension Tests
      name: phpstan-phpunit
      script:
        - ./e2e/test-extension.sh 'https://github.com/phpstan/phpstan-phpunit.git'

    - stage: Extension Tests
      name: phpstan-strict-rules
      script:
        - ./e2e/test-extension.sh 'https://github.com/phpstan/phpstan-strict-rules.git'

    - stage: Extension Tests
      name: phpstan-mockery
      script:
        - ./e2e/test-extension.sh 'https://github.com/phpstan/phpstan-mockery.git'

    - stage: Extension Tests
      name: phpstan-doctrine
      script:
        - ./e2e/test-extension.sh 'https://github.com/phpstan/phpstan-doctrine.git'

    - stage: Extension Tests
      name: phpstan-symfony
      script:
        - ./e2e/test-extension.sh 'https://github.com/phpstan/phpstan-symfony.git'

    - stage: Extension Tests
      name: phpstan-php-parser
      script:
        - ./e2e/test-extension.sh 'https://github.com/phpstan/phpstan-php-parser.git'

    - stage: Extension Tests
      name: phpstan-deprecation-rules
      script:
        - ./e2e/test-extension.sh 'https://github.com/phpstan/phpstan-deprecation-rules.git'

    - stage: Extension Tests
      name: phpdoc-parser
      script:
        - ./e2e/test-extension.sh 'https://github.com/phpstan/phpdoc-parser.git'

    - stage: Extension Tests
      name: phpstan-nette
      script:
        - ./e2e/test-extension.sh 'https://github.com/phpstan/phpstan-nette.git'

    - stage: Extension Tests
      name: phpstan-dibi
      script:
        - ./e2e/test-extension.sh 'https://github.com/phpstan/phpstan-dibi.git'

    - stage: Extension Tests
      name: phpstan-webmozart-assert
      script:
        - ./e2e/test-extension.sh 'https://github.com/phpstan/phpstan-webmozart-assert.git'

    - stage: Extension Tests
      name: phpstan-beberlei-assert
      script:
        - ./e2e/test-extension.sh 'https://github.com/phpstan/phpstan-beberlei-assert.git'

    - stage: Draft The Release
      script: skip
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file:
            - phpstan.phar
            - phpstan.phar.asc
          skip_cleanup: true
          draft: true
          name: $TRAVIS_TAG
          on:
            tags: true

cache:
  directories:
    - $HOME/.composer/cache
