# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Integration tests"

on:
  pull_request:
  push:
    branches:
      - "master"
    paths-ignore:
      - 'issue-bot/**'
      - 'website/**'
      - 'playground-api/**'
      - 'playground-runner/**'

jobs:
  integration-tests:
    name: "Integration Tests"

    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 7.4
        script:
          - |
            git clone https://github.com/nunomaduro/larastan.git e2e/integration/repo
            cd e2e/integration/repo
            git checkout ca98347313e20fe84daf22c08a31a550153f3be9
            composer install
            ../../../phpstan.phar analyse -c ../larastan.neon
          - |
            git clone https://github.com/slevomat/coding-standard.git e2e/integration/repo
            cd e2e/integration/repo
            git checkout c6282eefa680e3c982ea41a8df4ce2e5402eed6a
            composer install
            composer require --dev phpstan/phpstan:^1.0 phpstan/phpstan-strict-rules:^1.0 phpstan/phpstan-phpunit:^1.0 phpstan/phpstan-deprecation-rules:^1.0
            ../../../phpstan.phar analyse -c ../slevomat-cs.neon -l 7 SlevomatCodingStandard
            ../../../phpstan.phar analyse -c build/PHPStan/phpstan.tests.neon -l 7 tests
          - |
            git clone https://github.com/composer/composer.git e2e/integration/repo
            cd e2e/integration/repo
            git checkout d3c176ec696c2aaf98e482fed44edf92e8975c34
            composer install
            composer config platform --unset && composer update
            bin/composer require --dev phpunit/phpunit:^7.5 --with-all-dependencies
            bin/composer require --dev phpstan/phpstan-phpunit
            ../../../phpstan.phar analyse -c ../composer.neon src tests
          #- |
          #  git clone https://github.com/nextras/orm.git e2e/integration/repo
          #  cd e2e/integration/repo
          #  git checkout 336140091ecc6053ec5161b3f48e2803f13be3ad
          #  composer install
          #  ../../../phpstan.phar analyse -c .phpstan.neon
        include:
          - php-version: 8.0
            script: |
              git clone https://github.com/rectorphp/rector-src.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 430041fd553aca364c8fd2379cf854ae320c247b
              cp ../rector-composer.lock composer.lock
              composer install
              ../../../phpstan.phar analyse -c ../rector.neon
          - php-version: 8.0
            script: |
              git clone https://github.com/sebastianbergmann/phpunit.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 9.5.6
              export COMPOSER_ROOT_VERSION=9.5.6
              composer install
              ../../../phpstan.phar analyse -l 8 -c ../phpunit.neon src tests
          - php-version: 8.0
            script: |
              git clone https://github.com/pmmp/PocketMine-MP.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 01fe497c491c6e6ab6922fc6cc441d812a394f73
              composer install --ignore-platform-reqs
              composer config minimum-stability dev
              composer require --dev phpstan/phpstan:^1.0 phpstan/phpstan-strict-rules:^1.0 phpstan/phpstan-phpunit:^1.0 --ignore-platform-reqs
              ../../../phpstan.phar analyse -c ../pocketmine.neon --memory-limit=2G
          - php-version: 8.0
            script: |
              git clone https://github.com/laravel/framework.git e2e/integration/repo
              cd e2e/integration/repo
              git checkout 932e601d1e8063a51cbce95136d54367d6f3ece4
              composer install
              ../../../phpstan.phar analyse -c ../laravel.neon

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Tests"
        run: "${{ matrix.script }}"
