# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Run Issue bot"

on:
  repository_dispatch:
    types: [ run_issue_bot ]

concurrency: issue_bot

jobs:
  issue-bot:
    name: "Issue bot"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.0"

      - name: "Install dependencies"
        working-directory: ./issue-bot
        run: "composer install --no-interaction --no-progress --no-dev"

      - name: "Run bot"
        working-directory: ./issue-bot
        env:
          GITHUB_PAT: ${{ secrets.ISSUE_BOT_TOKEN }}
          PHPSTAN_SRC_COMMIT_BEFORE: ${{ github.event.client_payload.phpstan_src_commit_before }}
          PHPSTAN_SRC_COMMIT_AFTER: ${{ github.event.client_payload.phpstan_src_commit_after }}
        run: "php run.php"
